## Ammo

- type: latheRecipe
  id: CartridgePistolRubber
  result: CartridgePistolRubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeMagnumRubber
  result: CartridgeMagnumRubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeLightRifleRubber
  result: CartridgeLightRifleRubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgeRifleRubber
  result: CartridgeRifleRubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5
    
- type: latheRecipe
  id: MagazineBoxPistolRubber
  result: MagazineBoxPistolRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300
    
- type: latheRecipe
  id: MagazineBoxMagnumRubber
  result: MagazineBoxMagnumRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300
    
- type: latheRecipe
  id: MagazineBoxRifleRubber
  result: MagazineBoxRifleRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600
    
- type: latheRecipe
  id: MagazineBoxLightRifleRubber
  result: MagazineBoxLightRifleRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600
    
- type: latheRecipe
  id: ShellShotgunBeanbag
  result: MagazineBoxLightRifleRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600

- type: latheRecipe
  id: M492Magazine
  result: M492Magazine
  category: Ammo
  completetime: 5
  materials:
    Steel: 1580
    
- type: latheRecipe
  id: M492MagazineEmpty
  result: M492MagazineEmpty
  category: Ammo
  completetime: 5
  materials:
    Steel: 45

- type: latheRecipe
  id: M492MagazineUranium
  result: M492MagazineUranium
  category: Ammo
  completetime: 5
  materials:
    Steel: 25
    Plastic: 980
    Uranium: 980

- type: latheRecipe
  id: M492MagazineIncendiary
  result: M492MagazineIncendiary
  category: Ammo
  completetime: 5
  materials:
    Steel: 45
    Plastic: 1510
## Weapons

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponIonRifle
  result: WeaponIonRifle
  materials:
    Steel: 2000
    Glass: 1000
    Gold: 1000
    Silver: 500
    
- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponIonCarbine
  result: WeaponIonCarbine
  materials:
    Steel: 1500
    Gold: 1000
    Silver: 1000
    
- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserImmolator
  result: WeaponLaserImmolator
  materials:
    Steel: 2000
    Plasma: 1000
    Silver: 1000
    
- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponDecloner
  result: WeaponDecloner
  materials:
    Steel: 2500
    Glass: 2500
    Plasma: 2500
    Silver: 2500
    Gold: 1000
    Diamond: 1000